.TH LIBSHA2 7 2022-07-07 libsha1
.SH NAME
libsha2 \- SHA-2 hashing library
.SH DESCRIPTION
.B libsha1
is an implementation of the SHA-2 family hashing functions:
SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, and SHA-512/256;
with support for state marshalling and HMAC.
.SH SEE ALSO
.BR libsha2.h (0),
.BR libsha2_algorithm_output_size (3),
.BR libsha2_behex_lower (3),
.BR libsha2_behex_upper (3),
.BR libsha2_digest (3),
.BR libsha2_hmac_digest (3),
.BR libsha2_hmac_init (3),
.BR libsha2_hmac_marshal (3),
.BR libsha2_hmac_unmarshal (3),
.BR libsha2_hmac_update (3),
.BR libsha2_init (3),
.BR libsha2_marshal (3),
.BR libsha2_state_output_size (3),
.BR libsha2_sum_fd (3),
.BR libsha2_unhex (3),
.BR libsha2_unmarshal (3),
.BR libsha2_update (3)
